### ISSUE TITLE
PDF download not working

### ISSUE THREAD

**Issue by ramarro** [GladistonXD/perlego-download#11]
Pdf download isn't working for some books.

The counter remains stuck on 0/n, therefore the exported html is empty.

For the same books, ePub works fine.

**Comment by GladistonXD** [comment]
Could you send a PDF book that doesn't work?

**Comment by ramarro** [comment]
https://ereader.perlego.com/1/book/3740247/

**Comment by GladistonXD** [comment]
> https://ereader.perlego.com/1/book/3740247/

Here this ePub is normal, checked if the latest version was downloaded, I updated it a few days ago.

**Comment by RuiBrunoSantos** [comment]
U are just top Gladiston! 

I wish to see my projects made by you :P
