### ISSUE TITLE
ePub to PDF

### ISSUE THREAD

**Issue by MajidAmin112** [GladistonXD/perlego-download#13]
Hello Team,

is there any way to convert epub to pdf because I epub format is not readable. Please do the needful. 

Waiting for positive response.

**Comment by GladistonXD** [comment]
> Hello Team,
> 
> is there any way to convert epub to pdf because I epub format is not readable. Please do the needful.
> 
> Waiting for positive response.

How is the format not readable? The downloaded format is .html if a file has been downloaded, just open and print it in PDF.
