### ISSUE TITLE
Hyperlinks causing wrong formatting/styles when downloading .epub

### ISSUE THREAD

**Issue by leslie3982** [GladistonXD/perlego-download#15]
Hi [GladistonXD],

Sorry to disturb you again. I had another issue when downloading .epub files. When opened the downloaded .html page and checked, I saw some part of the file seemed to be in wrong styles/formatting.

Specificly, in this book: https://ereader.perlego.com/1/book/1589856 

**_*original book:_** 
![image](https://github.com/user-attachments/assets/a3fd4787-9120-4326-9e0e-3b7004ec4dc0)

**_*downloaded html page:_** 
![image](https://github.com/user-attachments/assets/5b17ae37-e88a-4305-8586-1391d0991d84)

I noticed that the wrong styles started from citation no.6 (it's not seperated from no.5 as in the original book and some content like the text link for citation no.5 was "eaten" ) and the remaining parts of the file was underlined. 

I guess the main cause perhaps lays in the _a href tags_ or _hyperlinks_ in the original epub. As in this image below, the html codes of the other parts included the hyperlink of citation no.5 (making them have the same styles).

![image](https://github.com/user-attachments/assets/e223e6c7-c292-4ca6-951c-b0c0419904e6)

I also checked with some more epub files on Perlego and still got same issue with hyperlinks - leading to wrong styles and formatting of the file. Some books even had wrong-formatted parts dispersed not in the rest of the file but in various content (mainly in Notes/Citation, Chapter Headings...). And not all the hyperlinks having issues. Some hyperlinks still appeared in proper formatting as in the original.

I tried editing the codes in Calibre to reformat the wrong parts but it's really tough and time-consuming when I had to check and fix manually. I have no knowledge of coding and programming so sorry if my issue make you confused.

Would you mind helping me to check on this? I'm really really grateful for what you did and looking forward to hearing from you. If I can do anything to support, please tell me.

Have a good day :D

**Comment by GladistonXD** [comment]
Interesting at the time, I didn't pay attention to external links, just the images, I made a correction to the code, I will soon add a donate option for anyone who wants to do it, test the code and tell me if it solved it.

**Comment by leslie3982** [comment]
Hi GladistonXD,

Sorry for the delay. I was busy in the past week and already checked your update. It worked perfectly. I would like to thank you so much for what you have done so far.

I saw your donate option and wanted to make a donation for your support but when I clicked on and processed, there's a notification saying something like "Donations to this recipient are not supported in this country" (cause I'm Vietnamese and I'm not getting used to Paypal quite well). May I have your Paypal username or id or any indicator that I can use to find your account? 

 ---
I feel that I'm bothering you a lot but it seems like I got another problem with .epub files :( really sorry for keeping raising new issues... hope that you can have time to help me check on this.
 
Until your latest update, the extension has worked really well with almost my reading list except for this one: https://ereader.perlego.com/1/book/1589828

When I ran the extension with epub files, there were usually some "stuck" moments like below:

![image](https://github.com/user-attachments/assets/9b2d71b7-f312-4a8d-8602-fb73f80741a7)

But with this book, the extension seemed to stop here (not continue auto-scrolling despite what I tried: refreshing the page, scrolling manually, move to next/previous chapters...); the process bar did not go up as well so I could not finish scanning the book.

![image](https://github.com/user-attachments/assets/f2f135bf-164b-4c80-954c-ccb21ee20778)

I recognized that when the page was first stuck and I tried refreshing it, the URL changed:

![image](https://github.com/user-attachments/assets/c02b5082-67d9-40a4-8398-68d5ff4ba9fb)

I also looked at the content of table and saw that the stuck point began at chapter 11 and coincidentally, it had 2 heading tags at the same level at the beginning of the page ("Creating and financially quantifying value propositions" + "Des Evans, former CEO...") when previous chapter didn't. I wondered if these reasons made the extension not to work.

Could you help me with this issue? Many thanks in advance. Looking forward to hearing from you.

**Comment by GladistonXD** [comment]
Hello, the problem is in the book itself, there are 9 paragraphs with errors and you cannot interact, in this case you would have to report the problem to the website so they can fix the book:
![image](https://github.com/user-attachments/assets/43d91f9b-be54-4789-b9c9-5753aab56fd4)

Of course, this is my paypal email if you want to contribute to the project: gladistonalvesleal@gmail.com

**Comment by leslie3982** [comment]
Hi bro, 

I reported the problem to the internal team and they fixed it. I haven't thought the book itself was broken lol :))))

Thanks for your guidance!

I just sent a donation for your support. Could you please check whether you receive it? (this is the 1st time I send money via Paypal). Although it's just a small amount because I'm unemployed now but still want to show my appreciation for what you did. I'll send you more when I have some more money.

-----
So sorry to disturb you again :(( I have a small issue with images in epub.

When I try with this book: https://ereader.perlego.com/1/book/4367270

With some images, the downloaded book seems to have images of worse quality than the orgininal ones. The example in the Figure 4.8 below. When on Perlego site, the image is good and of high quality

![image](https://github.com/user-attachments/assets/de489798-3ad4-46e9-aaee-6166c7305a66)



When downloaded and view html file in browser, the image seems to be compressed and of lower quality making the text kinda blurry and hard to read (in some other images it's too blurry that I can not read the content).

![image](https://github.com/user-attachments/assets/dc500e20-47d1-4504-8fbd-585f317b4ff7)



Checking the page source, when loading the image on Perlego, the URL is https://api.perlego.com/assets/asset?session=fb58f36ee9af5247c2c5d5bd426e77bad55adccc4aec56d1fa6d45c43913a37a&fileId=39fbbc33a173bb0ab7888a0b2ad5769e and the original size is 1471x901

![image](https://github.com/user-attachments/assets/21cb6660-570d-4725-a702-fb77acbcdb02)

![image](https://github.com/user-attachments/assets/9ab34d27-be33-41c0-9b27-83a975de7452)



When open downloaded html, the image is in smaller size 1000x612 and the URL was changed https://api.perlego.com/assets/asset?session=0a6046b81c9dc976f63f63741a8b89f8aac223ba85193884692ab5c91dd37518&fileId=88018ef119a379fd0703e4141ef9d40a

![image](https://github.com/user-attachments/assets/677247c3-be78-4fea-a139-2a50d0f4c26c)

![image](https://github.com/user-attachments/assets/b3a5a9c1-b33d-49ee-a6da-2e74ceb26375)



One more thing that I found: When viewing the book on Perlego in developing mode, there are 2 tags (src) and (srcset) with the same URL. If I click on both, the images are all 1471x901, but when I hover the moose to each URL and choose Open in new tab, the URL in (src) shows the image of the size 1471x901 but the URL in (srcset) shows the 1000x612 image as in the downloaded html file. In downloaded html file, there's only one (src) tag with the new URL of the 1000x612 image.

I know that there might be some image compression or resize to make the images fit to the page width. In spite of that things, on Perlego the images still display at better quality than in the downloaded html.

Do you know any ways to fix this? Could you help me to review on this issue? Many thanks in advance!

**Comment by GladistonXD** [comment]
Problem solved, find any other bug let me know. yes thanks for the donation and collaboration with the project. 😄

**Comment by leslie3982** [comment]
Thank you so much much much for your great work and support. Glad to collaborate with you too :D all the best to you
