### ISSUE TITLE
epub related problem

### ISSUE THREAD

**Issue by MajidAmin112** [GladistonXD/perlego-download#16]
when I try to save the ebook downloaded from epub format, So it spoils the Adjustments. screenshot attached. How to resolve this issue.

![Screenshot 2024-09-17 142522](https://github.com/user-attachments/assets/cbd764f6-c251-4839-9979-714729e901aa)

**Comment by GladistonXD** [comment]
In all books or just a specific one?

**Comment by MajidAmin112** [comment]
All books giving the same issue, please resolve it. Thank you

**Comment by GladistonXD** [comment]
I don't have any credentials for testing, can you tell me if this problem is recent? If you're using it for the first time and have already had this problem, you can try using Chrome Portable, it could be a font problem.

**Comment by MajidAmin112** [comment]
I am facing this issue from 2 months and all epub having the same issue and its the recent.

**Comment by GladistonXD** [comment]
Use this chrome send me feedback [https://portableapps.com/apps/internet/google_chrome_portable]()

**Comment by MajidAmin112** [comment]
Let me check and update you. Thank you

**Comment by MajidAmin112** [comment]
I have checked now and its giving the same things. 

![Screenshot 2024-09-21 105550](https://github.com/user-attachments/assets/c686ce67-8466-4e79-b279-89506e86ff5e)
