### ISSUE TITLE
epub related problem

### ISSUE THREAD

**Issue by MajidAmin112** [GladistonXD/perlego-download#17]
same thing happening in portable chrome. here is screenshot. I disable header and footer as well but same issue.

**Comment by MajidAmin112** [comment]
kindly resolve this issue thank you.

**Comment by GladistonXD** [comment]
Could you provide me with the HTML file? I have some logins and passwords, but Perlego now sends a confirmation password to the email and I do not have access to these emails to test the extension since the credentials were shared by users.

**Comment by GladistonXD** [comment]
If I understand your problem correctly, it is after converting to PDF, right? It could be the type of conversion, what I recommend is direct conversion via "save as PDF". I do not recommend conversions via Adobe PDF or Microsoft print PDF, this could be the cause of the formatting change.

**Comment by MajidAmin112** [comment]
I tried to save as pdf but same problem. I need your email to share with you.

**Comment by GladistonXD** [comment]
> I tried to save as pdf but same problem. I need your email to share with you.

You can send it to: 987654321gladiston@gmail.com

**Comment by MajidAmin112** [comment]
> > I tried to save as pdf but same problem. I need your email to share with you.
> 
> You can send it to: [987654321gladiston@gmail.com](mailto:987654321gladiston@gmail.com)

Sorry for late reply email send to you.

**Comment by GladistonXD** [comment]
I released the script for converting EPUB to PDF https://github.com/GladistonXD/html2pdfconverter
