### ISSUE TITLE
Epub Download

### ISSUE THREAD

**Issue by MikeCoreTV** [GladistonXD/perlego-download#18]
any way to download the epub with each labeled page in Perlego being present and separated by page in the HTML?

it seems to just entire chapters blocked together, which when it comes to citation makes it very hard to use.

**Comment by GladistonXD** [comment]
It is possible to edit the .html file and separate it by page, but the Epub model is not like the separate PDF, it is a direct file separated by indexes, the most you can do is edit the font size to make it similar to the pagination quality, I can create a script in python to convert the images to base64 so they are saved forever in the .html file but depending on where you use it it is not as viable as a .pdf

**Comment by MikeCoreTV** [comment]
Yeah, I was just hoping to fit whatever the epub considers a page to be put into a single image each so I can cite it and re-index it myself in pdfxchange because the elongated masses of chapters in a textbook aren't viable for me. Would the script you mentioned be a decent solution to that?

**Comment by GladistonXD** [comment]
The script mentioned would only be to keep the .html file permanently without expiring the images, I don't know if it would solve your problem.

**Comment by MikeCoreTV** [comment]
Ah, no it wouldn't. Thank you for the replies though! I'll just have to figure something out.
This tool was a life saver non-the-less!

**Comment by GladistonXD** [comment]
I made a script to convert .html EPUB to PDF with bookmarks maybe it will help https://github.com/GladistonXD/html2pdfconverter

**Comment by masteoo** [comment]
@GladistonXD hello, sorry, could you suggest a way to convert big html file (1000 pages) on my adroid tab please? My pc is not powerful. Thanks

**Comment by GladistonXD** [comment]
> @GladistonXD hello, sorry, could you suggest a way to convert big html file (1010 pages) on my adroid tab please? My pc is not powerful. Thanks

You can edit the .html file and split it into 2 then convert it to pdf and merge the two pdf

**Comment by masteoo** [comment]
@GladistonXD thanks for the feedback. How can I split a long html ebook in my S Tab please?

**Comment by GladistonXD** [comment]
> @GladistonXD thanks for the feedback. How can I split a long html ebook in my S Tab please?

It can be any text editor, .html is like a .txt file but you can use "QuickEdit" for more complete editing.

**Comment by GladistonXD** [comment]
> @GladistonXD thanks but I have error "not enough memory" :( .. but html file is only 100mb

You can split the .html text into multiple parts until it doesn't exceed Chrome's cache memory, or you can try opening it in Firefox.

**Comment by masteoo** [comment]
@GladistonXD thanks but don't know how to open in multipe parts...can I send you the file on Telegram? @proseccodoc

**Comment by GladistonXD** [comment]
> [@GladistonXD](https://github.com/GladistonXD) thanks but don't know how to open in multipe parts and with Calibre not working...

Send me this email: 987654321gladiston@gmail.com

**Comment by masteoo** [comment]
@GladistonXD ok thanks, sent. Could you please cancel your previous comment with my Telegram nickname please?

**Comment by masteoo** [comment]
@GladistonXD thanks, I will try to convert.. did you use QuickEdit to split?
