### ISSUE TITLE
Issue on ePub Files

### ISSUE THREAD

**Issue by ITcafee** [GladistonXD/perlego-download#19]
How to resolve these issues

1. Perlego Session Links on different pages, 
2. ePub page setting diffent from text.

screenshot attached
![Screenshot 2024-12-15 122418](https://github.com/user-attachments/assets/40d6af93-855c-4bfb-bfc1-c737b9226391)
![Screenshot 2024-12-15 123047](https://github.com/user-attachments/assets/226afd60-95d9-441b-b1f4-246dfc8b2327)

**Comment by GladistonXD** [comment]
From what I understand, there are links to a Perlego API appearing in the raw file, but not directly on the site? If these links are not original to the page, a small change in the code can remove them, but I would need the raw .html file for that.

**Comment by ITcafee** [comment]
Please share your email so I can send you html file and please check autual page adjustments as well.

**Comment by GladistonXD** [comment]
You can send it here 987654321gladiston@gmail.com

**Comment by ITcafee** [comment]
email sent to your good self.

**Comment by GladistonXD** [comment]
> email sent to your good self.

Generate a new .html file apparently this is a new image API I need a valid session to fix

**Comment by ITcafee** [comment]
I generate it 5 minutes ago.

**Comment by GladistonXD** [comment]
Stranger here says the session has expired.

**Comment by ITcafee** [comment]
Let me generate it again and send you

**Comment by GladistonXD** [comment]
I made a correction, see if it solved the problem

**Comment by ITcafee** [comment]
Thank you so much, one more thing can you convert the epub book like pdf, epub page setting not correctly saving.
