### ISSUE TITLE
Comma at the end of every page

### ISSUE THREAD

**Issue by H9RuH2d** [GladistonXD/perlego-download#5]
Hello! First of all, thank you very much for this extension -- it works great!

I just wanted to report that I seem to be getting a comma at the end of every page of the PDF (it shows up in the HTML too)

Here is an image of a blank page. The comma is in the bottom left. It's in the same spot on every page.

<img width="992" alt="image" src="https://github.com/GladistonXD/perlego-download/assets/151493782/1888e4b5-eb12-454b-b415-966484ae1a1f">

**Comment by GladistonXD** [comment]
> Hello! First of all, thank you very much for this extension -- it works great!
> 
> I just wanted to report that I seem to be getting a comma at the end of every page of the PDF (it shows up in the HTML too)
> 
> Here is an image of a blank page. The comma is in the bottom left. It's in the same spot on every page.
> 
> <img alt="image" width="992" src="https://user-images.githubusercontent.com/151493782/284130393-1888e4b5-eb12-454b-b415-966484ae1a1f.png">

Does it appear to you in all books or just in a specific one?

**Comment by H9RuH2d** [comment]
I just tried another PDF and got the same result. Doesn't happen with EPUBs. It seems like there's a comma being inserted between every `<br>` and the next `<div>`. For the time being I just used find/replace in VS Code to get rid of all of them, but pretty sure this can be taken care of in the extension itself?

**Comment by GladistonXD** [comment]
> I just tried another PDF and got the same result. Doesn't happen with EPUBs. It seems like there's a comma being inserted between every `<br>` and the next `<div>`. For the time being I just used find/replace in VS Code to get rid of all of them, but pretty sure this can be taken care of in the extension itself?

I no longer have credentials for testing, but you can send an .html file and I will analyze it and make corrections in the code.

**Comment by H9RuH2d** [comment]
Will send it a bit later (mention me if I forget). Btw you can get a free trial, but it seems to not be available in some countries. I had to use a VPN.

**Comment by GladistonXD** [comment]
The output was adding arrays, I hadn't noticed that, I made a small correction https://github.com/GladistonXD/perlego-download/commit/af0c2b0b4cbd0b6a573cfae0a73f5e5bb287c3b7
