### ISSUE TITLE
Can't find any page

### ISSUE THREAD

**Issue by Chri0044** [GladistonXD/perlego-download#6]
I tried the extension but when I choose PDF or e-PUB it is stuck on 0/0 pages found. Any solution?
![Screenshot (129)](https://github.com/GladistonXD/perlego-download/assets/153191430/6514a37f-3ba3-4a78-80b9-527f5c2920ac)

**Comment by GladistonXD** [comment]
Are you using the default Google Chrome? Apparently your Chrome is not allowing you to capture the page.

**Comment by Chri0044** [comment]
> Are you using the default Google Chrome? Apparently your Chrome is not allowing you to capture the page.

Yes I am. I also tried to look insiede the extension settings, but everything looks good to me. I also tried with different books but there's no difference. Maybe Perlego patched your extension :(

**Comment by GladistonXD** [comment]
> Yes I am. I also tried to look insiede the extension settings, but everything looks good to me. I also tried with different books but there's no difference. Maybe Perlego patched your extension :(

Here it is working normally, apparently this is a problem with some automation permissions in your Chrome.
![image](https://github.com/GladistonXD/perlego-download/assets/50533550/a13b0b9b-3338-4b41-a917-2df32b733120)

**Comment by GladistonXD** [comment]
If it's a permissions issue, try using a chrome portable:
https://portableapps.com/de/apps/internet/google_chrome_portable

**Comment by Chri0044** [comment]
> If it's a permissions issue, try using a chrome portable: https://portableapps.com/de/apps/internet/google_chrome_portable

You are right, now it finds 179 pages but still says that i am at page 0. I tried to reload the page at /3 as you suggested in the guide but still stuck on 0 even if I scroll all the way down, don't know what I am doing wrong now, thanks for your patience 
![Screenshot (130)](https://github.com/GladistonXD/perlego-download/assets/153191430/7967ca0f-21ce-4390-8909-2f474582a2e6)

**Comment by Chri0044** [comment]
-

> > If it's a permissions issue, try using a chrome portable: https://portableapps.com/de/apps/internet/google_chrome_portable
> 
> You are right, now it finds 179 pages but still says that i am at page 0. I tried to reload the page at /3 as you suggested in the guide but still stuck on 0 even if I scroll all the way down, don't know what I am doing wrong now, thanks for your patience ![Screenshot (130)](https://private-user-images.githubusercontent.com/153191430/288831997-7967ca0f-21ce-4390-8909-2f474582a2e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5Njg3OTQsIm5iZiI6MTcwMTk2ODQ5NCwicGF0aCI6Ii8xNTMxOTE0MzAvMjg4ODMxOTk3LTc5NjdjYTBmLTIxY2UtNDM5MC04OTA5LTJmNDc0NTgyYTJlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QxNzAxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODJhOGViZDY0YjljZTEzN2I0YmNkMzJhMjY3NzRlMWIwYTFkMmVmMjkxZGZkZWNhOWU2NDNhYTc0ZjliZTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BPnBWqmMj5-BouIZAKpSed2oqFia-b0HJ32aTx8gFnU)

I am just stupid, now it works perfectly, thanks for your help :)

**Comment by GladistonXD** [comment]
No problem :)
