### ISSUE TITLE
Saving as HTML - Is this correct?

### ISSUE THREAD

**Issue by Rickycoe123** [GladistonXD/perlego-download#7]
Just sorted out the scroll to page X. Fixed with Chrome portable. (Y)

Having one issue "issue" where either Epub export or PDF export just returns a Perlego.html. 

Running through Calibre to convert to epub/mobi and loses images... (not your problem). 

Can you explain is the .html normal? or should it be exported to pdf/epub?

**Comment by GladistonXD** [comment]
> Just sorted out the scroll to page X. Fixed with Chrome portable. (Y)
> 
> Having one issue "issue" where either Epub export or PDF export just returns a Perlego.html. 
> 
> Running through Calibre to convert to epub/mobi and loses images... (not your problem). 
> 
> Can you explain is the .html normal? or should it be exported to pdf/epub?

The .html file is made to release printing, it does not generate the PDF on its own, if you do not print it after a few days the images stop working as they are generated with an expiration date.

**Comment by Rickycoe123** [comment]
Apologies if this re-opens the issues thread, 

Just confirm to me then this can be closed. 

I have run this through a HTML to PDF converter. If this is ok, I presume the images remain.. right?

**Comment by GladistonXD** [comment]
> Apologies if this re-opens the issues thread,
> 
> Just confirm to me then this can be closed.
> 
> I have run this through a HTML to PDF converter. If this is ok, I presume the images remain.. right?

You don't need to run a converter, just press Ctrl+P inside the open .html file and select "Save as pdf" and save, it's as if it were a normal printout of any internet page.

**Comment by oscarmorrison** [comment]
Thanks for your great work @GladistonXD 

Can you please confirm if this is correct behaviour. When I click .epub, I just get a html document. How do I convert this to epub (is that another step?, or do I need to use another bit of software?)

**Comment by GladistonXD** [comment]
> Thanks for your great work @GladistonXD
> 
> Can you please confirm if this is correct behaviour. When I click .epub, I just get a html document. How do I convert this to epub (is that another step?, or do I need to use another bit of software?)

Yes, it generates the .html file and through it you can use your own browser to print to PDF. If you don't do this last step, the book will not be used for a long time, so it is necessary to print to PDF, Just open the .html and press Ctrl+P or click on print and select save as PDF, you can edit the size and remove the pagination mark as well, it depends on each person's preference, the important thing is to print in PDF.

**Comment by oscarmorrison** [comment]
ok thank you @GladistonXD 

So print (save to pdf)
Import into Calibre (or something similar)
Convert to epub
