### ISSUE TITLE
Page getting Stuck 

### ISSUE THREAD

**Issue by docRajat** [GladistonXD/perlego-download#8]
this is book link https://ereader.perlego.com/1/book/3547401/1
page is getting stuck after 20 pages max i have try 3 page trick also not working and increasing the time also https://prnt.sc/Z--AuElid6kG can anybody download and give pdf

**Comment by GladistonXD** [comment]
Apparently it's a space problem where Chrome is installed, if you use Windows, try using Chrome Portable, https://github.com/GladistonXD/perlego-download/issues/6#issuecomment-1845673019 I no longer have credentials.

**Comment by docRajat** [comment]
First of all very thankful for the extension
Tried portable Google also same issue coming

**Comment by GladistonXD** [comment]
Do you have this problem only in this book or in all of them?
