### ISSUE TITLE
doesn't work for EPUB

### ISSUE THREAD

**Issue by stefan5588** [GladistonXD/perlego-download#9]
Many thanks for the script, it worked wonderfully till a few days ago! Unfortunately it doesn’t work anymore for EPUB titles, the progress bar gets stuck at the first page; I guess something has changed in the HTML layout - more specifically, the tag for “next chapter”?

**Comment by GladistonXD** [comment]
It's very likely that yes, they may have changed the name of the button in the source code, unfortunately I don't have the credentials to continue the project.

**Comment by stefan5588** [comment]
let's fix it, give me an email address, please.

**Comment by GladistonXD** [comment]
> let's fix it, give me an email address, please.

987654321gladiston@gmail.com

**Comment by stefan5588** [comment]
> > let's fix it, give me an email address, please.
> 
> [987654321gladiston@gmail.com](mailto:987654321gladiston@gmail.com)

email sent

**Comment by GladistonXD** [comment]
> email sent

Ok, I'll check the problem, as soon as I fix it, I'll update the script and return here.

**Comment by GladistonXD** [comment]
The problem was that removing the visible page counter, I made a correction, test it. @stefan5588

**Comment by stefan5588** [comment]
> The problem was that removing the visible page counter, I made a correction, test it. @stefan5588

It works great, thanks!!

**Comment by GladistonXD** [comment]
Ok, I was trying to find a way to automate PDF books, but I don't think it's possible to use 2 simultaneous users, so I'll leave it like that for now.

**Comment by stefan5588** [comment]
> Ok, I was trying to find a way to automate PDF books

You can test it now
